language: java
jdk: oraclejdk8
cache:
 directories:
   - $HOME/.m2
before_deploy:
  - mvn --batch-mode versions:set -DnewVersion=${TRAVIS_TAG:1} --settings .travis/settings.xml
  - mvn clean package -DskipTests --settings .travis/settings.xml
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "target/dm3270-lib-*.jar"
  skip_cleanup: true
  on:
    tags: true
